### ISSUE TITLE
Quote in description

### ISSUE THREAD

**Issue by akolpakov** [heynemann/generator-python-package#5]
If package description contain symbol ' it should be quoted in setup.py.

For example I have description: "Python client for Paynova's API."
Generated Setup.py is not valid: 
```python
description='Python client for Paynova's API.',
```

Should be:
```python
description='Python client for Paynova\'s API.',
```

**Comment by scorphus** [comment]
Thanks for reporting this issue, @akolpakov. I'll handle it asap.
