### ISSUE TITLE
specify packages and structure

### ISSUE THREAD

**Issue by MortalCatalyst** [heynemann/generator-python-package#6]
Is it possible to specify a requirements.txt and/or json file to specify packages and versions to install along with folder structure for app?

**Comment by scorphus** [comment]
@MortalCatalyst, generator-python-package does not create any requirements file. Required packages – along with their versions – should be listed in the setup.py file, for example:

```python
setup(
    # ...
    install_requires=[
        'flask>=0.10.1,<0.11.0',
        'pyyaml>=3.11,<3.12',
        'ujson>=1.33,<1.34.0',
        # ...
    ],
    # ...
)
```
